import adventure from "./adventure";
import attack from "./attack";
import dance from "./dance";
import db from "./db";
import equip from "./equip";
import heal from "./heal";
import hp from "./hp";
import inspect from "./inspect";
import inventory from "./inventory";
import list from "./list";
// import quest from "./quest";
import quests from "./quests";
// import renew from "./renew";
import set from "./set";
import shop from "./shop";

const commands = new Map();
commands.set("adventure", adventure);
commands.set("attack", attack);
commands.set("dance", dance);
commands.set("db", db);
commands.set("equip", equip);
commands.set("heal", heal);
commands.set("hp", hp);
commands.set("inspect", inspect);
commands.set("inventory", inventory);
commands.set("list", list);
// commands.set("quest", quest);
commands.set("quests", quests);
// commands.set("renew", renew);
commands.set("set", set);
commands.set("shop", shop);
export default commands;
