export const banditNames = [
  "Raul the Knuckles",
  "Norwyn the Silent",
  "Windham Straight Jacket",
  "Nigel Poison",
  "Jaiden Phantom",
  "Rusty Timothy",
  "Nine Lives Freddy",
  "Lucky Rodman",
  "Bullseye Jarod",
  "Moneybags Dwight",
  "Madison the Outlaw",
  "Hayes the Nightmare",
  "Nolan the Shark",
  "Tyne Ghost",
  "Denton Black Eyes",
  "Toothless Ackerley",
  "Pickpocket Theodore",
  "Jester Grant",
  "Blue Eyed Wesley",
  "Mad Eyed Dudley",
];
